POST http://localhost:3000/api/personatges
Content-Type: application/json


{
  "nom": "Swooper",
  "tipus": "Pluma",
  "velocitat": 0,
  "acceleracio": 1.4,
  "pes": 0,
  "monedas": 1.8,
  "miniturbo": 0.8,
  "maneig": 1.2
}