PUT http://localhost:3000/api/vehicles/69961ea7f15b737c27dcb2a8
Content-Type: application/json

{
    "content":"Vehicle actualizat subscribete",
    "important":true
}


### Malformed id
PUT http://localhost:3000/api/vehicles/6984857d2c724bf453dc335 
Content-Type: application/json

{
    "content":"Vehicle actualizat subscribete",
    "important":true
}
### Id not found

PUT http://localhost:3001/api/vehicles/6984857d2c724bf453dc3357 
Content-Type: application/json

{
    "content":"Vehicle actualizat subscribete",
    "important":true
}

